# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PlanoVoo
                                 A QGIS plugin
 PlanoVoo
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-07-30
        copyright            : (C) 2024 by Prof Cazaroli
        email                : prof.cazaroli@geoone.com.br
 ***************************************************************************/
"""

def classFactory(iface):
    from .PlanoVoo import PlanoVoo
    return PlanoVoo(iface)
